[package]
name = "keylogger"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = {version = "0.59.0", features = ["Win32_UI_WindowsAndMessaging"]}
windows = "0.60.0"
thiserror="2.0.11"
logger = {git = "https://github.com/P40b0s/logger.git"}